# Generated by Django 4.1.1 on 2023-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_created_time', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('role_name', models.CharField(blank=True, default='None', max_length=255, unique=True)),
                ('role_description', models.TextField(blank=True, default='Role description', null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
    ]
