# Generated by Django 4.1.1 on 2023-12-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_layer_data_mgt', '0005_application_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_description',
            field=models.TextField(default='Application description'),
        ),
    ]
