# Generated by Django 4.1.1 on 2023-12-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_layer_data_mgt', '0006_alter_application_application_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPipeling',
            fields=[
                ('training_pipeling_uid', models.UUIDField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('training_pipeling_created_time', models.DateTimeField(max_length=255)),
                ('training_pipeling_name', models.CharField(blank=True, default='TrainingPipeline name', max_length=255)),
                ('training_pipeling_description', models.TextField(default='TrainingPipeline description')),
                ('f_application_uid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central_layer_data_mgt.application')),
            ],
            options={
                'db_table': 'training_pipeline',
                'managed': True,
            },
        ),
    ]
