# Generated by Django 4.1.1 on 2023-12-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_layer_data_mgt', '0007_trainingpipeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_uid', models.UUIDField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('model_created_time', models.DateTimeField(max_length=255)),
                ('model_version', models.CharField(default='1.0', max_length=255)),
                ('model_file_path', models.TextField(default='/', max_length=255)),
                ('model_file_extension', models.CharField(default='h5', max_length=255)),
                ('model_access_token', models.CharField(default='None', max_length=255)),
                ('model_description', models.TextField(default='Model description')),
                ('model_published', models.BooleanField(default=False)),
                ('f_application_uid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central_layer_data_mgt.application')),
                ('f_training_pipeline_uid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central_layer_data_mgt.trainingpipeling')),
            ],
            options={
                'db_table': 'model',
                'managed': True,
            },
        ),
    ]
