# Generated by Django 4.1.1 on 2023-12-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_layer_data_mgt', '0008_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('model_performance_uid', models.UUIDField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('model_performance_created_time', models.DateTimeField(max_length=255)),
                ('model_performance_matrice', models.CharField(default='None', max_length=255)),
                ('model_performance_value', models.CharField(default='None', max_length=255)),
                ('f_model_uid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='central_layer_data_mgt.model')),
            ],
            options={
                'db_table': 'model_performance',
                'managed': True,
            },
        ),
    ]
