# Generated by Django 4.1.1 on 2023-12-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_layer_data_mgt', '0009_modelperformance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingPipeling',
            new_name='TrainingPipeline',
        ),
        migrations.RenameField(
            model_name='trainingpipeline',
            old_name='training_pipeling_created_time',
            new_name='training_pipeline_created_time',
        ),
        migrations.RenameField(
            model_name='trainingpipeline',
            old_name='training_pipeling_description',
            new_name='training_pipeline_description',
        ),
        migrations.RenameField(
            model_name='trainingpipeline',
            old_name='training_pipeling_name',
            new_name='training_pipeline_name',
        ),
        migrations.RenameField(
            model_name='trainingpipeline',
            old_name='training_pipeling_uid',
            new_name='training_pipeline_uid',
        ),
    ]
