# Generated by Django 4.1.1 on 2023-12-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_layer_data_mgt', '0010_rename_trainingpipeling_trainingpipeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='f_application_uid',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='f_training_pipeline_uid',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_file_path',
            field=models.TextField(default='/'),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='f_model_uid',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='model_performance_created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trainingpipeline',
            name='f_application_uid',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingpipeline',
            name='training_pipeline_created_time',
            field=models.DateTimeField(),
        ),
    ]
